include:
  - template: Jobs/SAST.gitlab-ci.yml #semgrep tool
  - template: Jobs/SAST-IaC.gitlab-ci.yml #kicks tool
  - template: Jobs/Secret-Detection.gitlab-ci.yml #gitleaks


variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  SECRET_DETECTION_HISTORIC_SCAN: "true"

stages:
  - build
  - test

my_github_triggered_job:
  stage: build
  script:  # Fixed: This was indented incorrectly
    - echo "This job runs when triggered by GitHub changes."
  rules:   # Fixed: This was indented incorrectly
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
